port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
ipv6: false
mode: rule
log-level: silent
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ""
bind-address: "*"
unified-delay: true
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  default-nameserver:
  - 1.1.1.1
  - 1.0.0.1
  - 8.8.8.8
  nameserver:
  - 8.8.8.8
  ipv6: false
  enhanced-mode: redir-host
  listen: 0.0.0.0:7874
  respect-rules: true
  fallback:
  - 8.8.8.8
  proxy-server-nameserver:
  - 114.114.114.114
  - 119.29.29.29
  - 8.8.8.8
  - 1.1.1.1
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - +.battlenet.com.cn
    - +.wotgame.cn
    - +.wggames.cn
    - +.wowsgame.cn
    - +.wargaming.net
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - +.nflxvideo.net
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.mcdn.bilivideo.cn"
    - +.media.dssott.com
proxies:
  - name: IKD
    type: trojan
    server: 162.159.140.159
    port: 443
    password: tupaiikd
    udp: true
    sni: id-ikd001.kegiatanja.my.id
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /trojan-go
      headers:
        Host: id-ikd001.kegiatanja.my.id

  - name: Ovh1
    type: trojan
    server: 162.159.140.159
    port: 443
    password: tupaisgdo
    udp: true
    sni: tro-sgdo002.tunggure.buzz
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /trojan-go
      headers:
        Host: tro-sgdo002.tunggure.buzz

  - name: UAS id
    type: trojan
    server: 162.159.140.159
    port: 443
    password: tupaisgdo
    udp: true
    sni: tro-sgdo002.tunggure.buzz
    skip-cert-verify: true
    network: ws
    ws-opts:
      path: /trojan-go
      headers:
        Host: tro-sgdo002.tunggure.buzz
proxy-groups:
  - name: MAIN
    type: select
    proxies:
      - IKD
      - UAS id
      - Ovh1
      - LOAD-BALANCE
      - FALLBACK
  - name: FALLBACK
    type: fallback
    url: http://www.gstatic.com/generate_204
    interval: 120
    proxies: 
      - UAS id
      - Ovh1
      - IKD
  - name: BEST PING
    type: url-test
    url: http://www.gstatic.com/generate_204
    interval: 120
    tolerance: 60
    proxies: 
      - UAS id
      - Ovh1
      - IKD
  - name: LOAD-BALANCE
    type: load-balance
    strategy: consistent-hashing
    url: http://www.gstatic.com/generate_204
    interval: 120
    proxies: 
      - UAS id
      - Ovh1
      - IKD
rules:
  - MATCH,MAIN
